#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/musta
#    username: postgres
#    password: tizi
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: postgresql
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  doc:
#      default-produces-media-type: application/json
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/bankdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  doc:
    default-produces-media-type: application/json


  mail:
   host: smtp.gmail.com
   port: 587
   username: ga
   password: flqk fqlf cwmf xwoo
   properties:
     mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
